### PR TITLE
fixing video url not found

### PR DESCRIPTION
**Pull request by farisamirmudin**

### CODE REVIEW

**Comment by CoolnsX** [comment]
@farisamirmudin already fixed in latest commit
```diff
diff --git a/dra-cla b/dra-cla
index ab28613..fe4096e 100755
--- a/dra-cla
+++ b/dra-cla
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-VERSION="2.1.0"
+VERSION="2.1.1"
 
 #######################
 # AUXILIARY FUNCTIONS #
@@ -140,7 +140,7 @@ decrypt_link() {
 	secret_key='3933343232313932343333393532343839373532333432393038353835373532'
 	iv='39323632383539323332343335383235'
 	ajax_url="$base_url/encrypt-ajax.php"
-	ajax=$(printf "%s" "$1" | sed -nE 's/.*id=(.*)&title.*/\1/p' | openssl enc -e -aes256 -K "$secret_key" -iv "$iv" | base64)
+	ajax=$(printf "%s" "$1" | sed -nE 's/.*id=([^&]*)&.*/\1/p' | openssl enc -e -aes256 -K "$secret_key" -iv "$iv" | base64)
 	data=$(curl -s -H "X-Requested-With:XMLHttpRequest" "$ajax_url" -d "id=$ajax" | sed -e 's/{"data":"//' -e 's/"}/\n/' -e 's/\\//g')
 	printf '%s' "$data" | base64 -d | openssl enc -d -aes256 -K "$secret_key" -iv "$iv" | sed -e 's/\].*/\]/' -e 's/\\//g' | tr '{|}' '\n' | sed -nE 's/\"file\":"([^"]*)".*label.*P.*/\1/p'
 }
```

**Comment by farisamirmudin** [comment]
yeah the same approach as mine, subscripting the URL until the first & sign instead of until title=

**Comment by CoolnsX** [comment]
Yup and I respect the changes u made but unfortunately it won't be merged now..

**Comment by farisamirmudin** [comment]
No problem

**Pull request closed without merging**
