### PR TITLE
mp4 download fix

### PR DESCRIPTION
**Pull request by HossainRizbi**

### CODE REVIEW

**Comment by CoolnsX** [comment]
Exactly what i would prefer

**Comment by CoolnsX** [comment]
Can u bump up the version

**Comment by CoolnsX** [comment]
Noice!! Arigato...

**Comment by HossainRizbi** [comment]
will it be good to use mx player instead of mpv on android

**Comment by CoolnsX** [comment]
U can and i would prefer vlc.. but if it's ur choice u can

**Comment by CoolnsX** [comment]
u hv to change contents in ```$PREFIX/bin/mpv``` to point to MX player..

**Comment by CoolnsX** [comment]
Go through this.. if u want to implement it..
https://mx.j2inter.com/api

**Comment by HossainRizbi** [comment]
i am already using it in my termux for ani-cli and dra-cla

**Comment by HossainRizbi** [comment]
but didn't publish it because it's propiratory staff

**Comment by CoolnsX** [comment]
Tbh MX player is good... But their recent UI + too much ads made me switch to vlc and later to mpv.. I think vlc will be a sweet spot as it supports title and video URL passing as intent.. it also supports subtitles through intents but it allows only local subtitles

**Comment by HossainRizbi** [comment]
I use the pro version so it works really well for me

**Comment by CoolnsX** [comment]
use whatever u like.. i m gonna update readme for the same..

**Pull request merged**
